/** CEFR A1–B1 相当の頻出 headNoun → 日本語。生成欠落時の補完用。 */
export const HEAD_NOUN_JA = {
  apple: 'りんご',
  bag: 'かばん',
  book: '本',
  bookstore: '書店',
  bottle: 'ボトル',
  box: '箱',
  bread: 'パン',
  bus: 'バス',
  butter: 'バター',
  chair: '椅子',
  cheese: 'チーズ',
  chicken: '鶏肉',
  class: '授業',
  coffee: 'コーヒー',
  computer: 'コンピュータ',
  desk: '机',
  door: 'ドア',
  email: 'メール',
  fish: '魚',
  food: '食べ物',
  friend: '友達',
  fruit: '果物',
  glass: 'グラス',
  homework: '宿題',
  information: '情報',
  juice: 'ジュース',
  key: '鍵',
  lesson: 'レッスン',
  letter: '手紙',
  luggage: '荷物',
  mail: '郵便',
  meat: '肉',
  milk: '牛乳',
  money: 'お金',
  music: '音楽',
  news: 'ニュース',
  paper: '紙',
  pen: 'ペン',
  phone: '電話',
  photo: '写真',
  pizza: 'ピザ',
  problem: '問題',
  question: '質問',
  rain: '雨',
  report: 'レポート',
  rice: '米',
  room: '部屋',
  salt: '塩',
  school: '学校',
  shop: '店',
  sugar: '砂糖',
  table: 'テーブル',
  tea: 'お茶',
  ticket: '切符',
  time: '時間',
  train: '電車',
  water: '水',
  weather: '天気',
  window: '窓',
  work: '仕事',
};

export function lookupHeadNounJa(headNoun) {
  if (!headNoun) return null;
  const key = String(headNoun).trim().toLowerCase();
  return HEAD_NOUN_JA[key] ?? null;
}
