/** Mock set for UI development and offline demo (prototype-derived, V-MOD-DYN uses §5.6.1 contract) */
export const MOCK_SET = {
  generatedAt: '2026-07-10T00:00:00Z',
  preset: 'noun',
  selectedTags: [
    'N-NP', 'N-UNC', 'N-QNT', 'V-TA', 'V-VOICE', 'V-MOD-DYN', 'V-MOD-DEO',
    'M-AGR', 'M-PRON-CASE', 'M-SEQ',
  ],
  tagAllocation: [
    'N-NP', 'N-UNC', 'N-QNT', 'V-TA', 'V-VOICE', 'V-MOD-DYN', 'V-MOD-DEO',
    'M-AGR', 'M-PRON-CASE', 'M-SEQ',
  ],
  items: [
    {
      id: 1,
      tag: 'N-NP',
      sceneTag: '買い物',
      functionTag: '情報を得る',
      contextEn: 'I was looking for a gift.',
      ja: '昨日、私は書店に行った。',
      template: 'I went to ___ yesterday.',
      headNoun: 'bookstore',
      headNounJa: '書店',
      countability: 'countable',
      gridVariant: 'article-singular',
      gridPatterns: ['a {n}', 'the {n}', '{n}', '{n}s'],
      options: [
        { key: 'A', text: 'a bookstore', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'the bookstore', correct: false, reasonCode: 'N_DEF_NEW', note: 'どの書店かは初めて話題に出る', appliedMeaning: '（相手がすでに知っている）例の書店に行った、という意味になる' },
        { key: 'C', text: 'bookstores', correct: false, reasonCode: 'N_NUM_SG', note: 'bookstore は可算名詞で、行ったのは1軒', appliedMeaning: '複数の書店を（同時に／はしごして）回った、という意味になる' },
        { key: 'D', text: 'the bookstores', correct: false, reasonCode: 'N_DEF_NEW', note: '限定性・数の両方が不適', appliedMeaning: '相手も知っている複数の書店を回った、という意味になる' },
      ],
    },
    {
      id: 2,
      tag: 'N-UNC',
      sceneTag: '空港',
      functionTag: '確認する',
      contextEn: 'The waiter is asking what she wants to drink.',
      ja: '水をください。',
      template: "I'd like ___ please.",
      headNoun: 'water',
      headNounJa: '水',
      countability: 'uncountable',
      gridVariant: 'some-any',
      gridPatterns: ['{n}', 'some {n}', 'any {n}', 'the {n}'],
      options: [
        { key: 'A', text: 'some water', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'water', correct: false, reasonCode: 'N_MARKER_MISMATCH', note: '勧誘・依頼では some water の方が自然', appliedMeaning: '水をください、という意味は通じるがやや不自然' },
        { key: 'C', text: 'a water', correct: false, reasonCode: 'N_UNCOUNTABLE', note: 'water は不可算名詞なので a は付かない', appliedMeaning: '文法的に成立せず、意味が確定しない（口語で「1杯の水」と伝わる場合もあるが正式には非文法）' },
        { key: 'D', text: 'the water', correct: false, reasonCode: 'N_DEF_NEW', note: '特定の水を指す文脈ではない', appliedMeaning: '話し手と聞き手の間で共通認識のある特定の水を指す意味になる' },
      ],
    },
    {
      id: 3,
      tag: 'N-QNT',
      sceneTag: '教室',
      functionTag: '情報を得る',
      contextEn: null,
      ja: '宿題はあまり多くない。',
      template: "I don't have ___ homework.",
      headNoun: 'homework',
      headNounJa: '宿題',
      countability: 'uncountable',
      options: [
        { key: 'A', text: 'much', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'many', correct: false, reasonCode: 'N_QNT_MISMATCH', note: 'homework は不可算名詞なので many は使えない', appliedMeaning: '文法的に成立しない（many は可算名詞専用）' },
        { key: 'C', text: 'few', correct: false, reasonCode: 'N_QNT_MISMATCH', note: 'homework は不可算なので few も使えない', appliedMeaning: '文法的に成立しない' },
        { key: 'D', text: 'little', correct: false, reasonCode: 'N_QNT_MISMATCH', note: 'little は不可算だが否定文では much とセットで使う', appliedMeaning: '「ほとんど宿題がない」ではなく「少しの宿題を持っていない」という不自然な意味になる' },
      ],
    },
    {
      id: 4,
      tag: 'V-TA',
      sceneTag: '職場',
      functionTag: '情報を得る',
      contextEn: 'The phone rang at 8pm.',
      ja: '電話が鳴ったとき、私は夕食を食べていた。',
      template: 'I ___ dinner when the phone rang.',
      options: [
        { key: 'A', text: 'was eating', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'ate', correct: false, reasonCode: 'V_ASPECT', note: '電話が鳴った瞬間に食事の途中であった継続を表せない', appliedMeaning: '食べたという1回の完結した行為になり、電話との時間関係が同時ではなくなる' },
        { key: 'C', text: 'have eaten', correct: false, reasonCode: 'V_TENSE', note: '現在完了で過去の1点との重ねができない', appliedMeaning: '「今までに食べたことがある」という現在時点での経験の意味になる' },
        { key: 'D', text: 'had eaten', correct: false, reasonCode: 'V_ASPECT', note: '過去完了だと『電話が鳴る前にすでに食べ終わっていた』になり継続でない', appliedMeaning: '電話が鳴る前に食事が完了していた、という順序の意味になる' },
      ],
    },
    {
      id: 5,
      tag: 'V-VOICE',
      sceneTag: '語学学校',
      functionTag: '確認する',
      contextEn: 'The teacher assigned the report to the class.',
      ja: 'そのレポートは金曜日までに書かれる必要がある。',
      template: 'The report ___ by Friday.',
      options: [
        { key: 'A', text: 'must be written', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'must write', correct: false, reasonCode: 'V_VOICE', note: '主語 the report が『書く側』になってしまう', appliedMeaning: '「レポートが（自ら）書かなければならない」という擬人化された非文法的な意味になる' },
        { key: 'C', text: 'is writing', correct: false, reasonCode: 'V_VOICE', note: '能動の進行で the report が主語だと成立しない', appliedMeaning: '「レポートが書いている最中だ」という不自然な意味になる' },
        { key: 'D', text: 'has written', correct: false, reasonCode: 'V_VOICE', note: '能動の現在完了、主語と態が合わない', appliedMeaning: '「レポートが（何かを）書き終えた」という擬人化された意味になる' },
      ],
    },
    {
      id: 6,
      tag: 'V-MOD-DYN',
      sceneTag: '寮生活',
      functionTag: '情報を得る',
      contextEn: 'Every morning before school, she practices.',
      ja: '彼女は毎朝ピアノを弾く。',
      template: 'She ___ the piano every morning.',
      baseVerb: 'play',
      poolUsed: ['(bare)', 'can', 'would', 'may'],
      options: [
        { key: 'A', text: 'plays', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'can play', correct: false, reasonCode: 'V_MOD_SENSE_MISMATCH', note: '能力の意味になり、日常習慣の叙述と噛み合わない', appliedMeaning: '「弾ける（能力がある）」という意味になる' },
        { key: 'C', text: 'would play', correct: false, reasonCode: 'V_MOD_TENSE_MISMATCH', note: '過去や仮定の距離感が入る', appliedMeaning: '「（昔は／もし〜なら）弾いただろう」という距離のある意味になる' },
        { key: 'D', text: 'may play', correct: false, reasonCode: 'V_MOD_TOO_WEAK', note: '不確実な可能性の意味になる', appliedMeaning: '「弾くかもしれない」という不確かな意味になる' },
      ],
    },
    {
      id: 7,
      tag: 'V-MOD-DEO',
      sceneTag: '空港',
      functionTag: '理由・目的を問う',
      contextEn: 'She might miss her flight because of traffic.',
      ja: '彼女は今すぐ空港へ向かわなければならない。',
      template: 'She ___ go to the airport now.',
      poolUsed: ['have to', 'must', 'should', 'may'],
      options: [
        { key: 'A', text: 'has to', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'must', correct: false, reasonCode: 'V_MOD_SOURCE_MISMATCH', note: '外部事情ではなく話者の主観的な必要性に聞こえる', appliedMeaning: '話者が「絶対に必要だ」と個人的に強く思っている、という意味になる' },
        { key: 'C', text: 'should', correct: false, reasonCode: 'V_MOD_TOO_WEAK', note: '助言レベルで、緊急の必要性が伝わらない', appliedMeaning: '「そうした方がいいよ」という助言程度の弱さになる' },
        { key: 'D', text: 'may', correct: false, reasonCode: 'V_MOD_SENSE_MISMATCH', note: '許可・可能性の意味になり、必要性が伝わらない', appliedMeaning: '「行ってもよい（許可）」という意味に変わってしまう' },
      ],
    },
    {
      id: 8,
      tag: 'M-AGR',
      sceneTag: '家庭',
      functionTag: '確認する',
      contextEn: null,
      ja: '棚の上の本たちは私のものだ。',
      template: 'The books on the shelf ___ mine.',
      options: [
        { key: 'A', text: 'are', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'is', correct: false, reasonCode: 'M_AGR_NUMBER', note: '主語の核 books（複数）と一致しない', appliedMeaning: '文法的に非文法（on the shelf は修飾句で主語の核ではない）' },
        { key: 'C', text: 'was', correct: false, reasonCode: 'M_AGR_NUMBER', note: '数の不一致に加え、過去時制へずれている', appliedMeaning: '「私のものだった」と過去のことになり、現在の所有を表せない' },
        { key: 'D', text: 'were', correct: false, reasonCode: 'V_TENSE', note: '数は合うが時制が過去', appliedMeaning: '「私のものだった」と過去のことになる' },
      ],
    },
    {
      id: 9,
      tag: 'M-PRON-CASE',
      sceneTag: 'レストラン',
      functionTag: '確認する',
      contextEn: 'Tom sat next to Sarah at dinner.',
      ja: 'サラは彼にワインを注いだ。',
      template: 'Sarah poured wine for ___.',
      options: [
        { key: 'A', text: 'him', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'he', correct: false, reasonCode: 'M_PRON_CASE', note: '前置詞 for の後ろは目的格', appliedMeaning: '非文法（主格は主語の位置でのみ使う）' },
        { key: 'C', text: 'his', correct: false, reasonCode: 'M_PRON_CASE', note: '所有格は名詞の前で使う', appliedMeaning: '「彼のワイン」という意味の断片になり、文が完結しない' },
        { key: 'D', text: 'himself', correct: false, reasonCode: 'M_PRON_CASE', note: '再帰代名詞は主語と同一の対象を指す', appliedMeaning: '「サラは彼自身（＝サラ自身が彼になったかのように）にワインを注いだ」という不自然な意味になる' },
      ],
    },
    {
      id: 10,
      tag: 'M-SEQ',
      sceneTag: 'キャリア',
      functionTag: '情報を得る',
      contextEn: null,
      ja: '彼は明日来ると言った。',
      template: 'He said he ___ come the next day.',
      options: [
        { key: 'A', text: 'would', correct: true, reasonCode: null, note: null, appliedMeaning: null },
        { key: 'B', text: 'will', correct: false, reasonCode: 'M_SEQ_TENSE', note: '主節が過去（said）なので従属節も過去にずらす', appliedMeaning: '現在から見た未来予測に聞こえ、時制の整合が取れない' },
        { key: 'C', text: 'comes', correct: false, reasonCode: 'M_SEQ_TENSE', note: '現在形は主節の過去と一致しない', appliedMeaning: '「彼は普段来る、と言った」という習慣の意味に取られてしまう' },
        { key: 'D', text: 'came', correct: false, reasonCode: 'V_ASPECT', note: '単純過去だと未来の意味を持たない', appliedMeaning: '「彼は翌日に来た、と言った」という完了済みの意味になる' },
      ],
    },
  ],
};
