/** Few-shot examples embedded in system prompt (appliedMeaning の手本) */
export const FEW_SHOT_EXAMPLES = [
  {
    id: 1,
    tag: 'N-NP',
    sceneTag: '寮生活',
    functionTag: '申し出る',
    contextEn: 'Your room looks very cold tonight.',
    ja: '毛布を持ってきてあげようか？',
    template: 'Do you want me to bring ___?',
    headNoun: 'blanket',
    headNounJa: '毛布',
    countability: 'countable',
    gridVariant: 'article-singular',
    gridPatterns: ['a {n}', 'the {n}', '{n}', '{n}s'],
    options: [
      { key: 'A', text: 'a blanket', correct: true, reasonCode: null, note: null, appliedMeaning: null },
      { key: 'B', text: 'the blanket', correct: false, reasonCode: 'N_DEF_NEW', note: '初出なので the は使えない', appliedMeaning: '（相手も知っている）例の毛布を持ってくる、という意味になる' },
      { key: 'C', text: 'blanket', correct: false, reasonCode: 'N_ARTICLE_REQUIRED', note: 'blanket は可算名詞の単数形なので冠詞が必要', appliedMeaning: '文法的に不完全で、意味が確定しない' },
      { key: 'D', text: 'blankets', correct: false, reasonCode: 'N_NUM_SG', note: '持ってくるのは1枚', appliedMeaning: '複数枚の毛布を持ってくる、という意味になる' },
    ],
  },
  {
    id: 2,
    tag: 'N-UNC',
    sceneTag: '家庭',
    functionTag: '確認する',
    contextEn: 'We need to cook dinner soon.',
    ja: '冷蔵庫にまだ米はある？',
    template: 'Is there ___ in the fridge?',
    headNoun: 'rice',
    headNounJa: '米',
    countability: 'uncountable',
    gridVariant: 'some-any',
    gridPatterns: ['{n}', 'some {n}', 'any {n}', 'the {n}'],
    options: [
      { key: 'A', text: 'any rice', correct: true, reasonCode: null, note: null, appliedMeaning: null },
      { key: 'B', text: 'rice', correct: false, reasonCode: 'N_MARKER_MISMATCH', note: '疑問文では any rice の方が自然', appliedMeaning: '米があるかどうかがやや不明瞭に聞こえる' },
      { key: 'C', text: 'a rice', correct: false, reasonCode: 'N_UNCOUNTABLE', note: 'rice は不可算名詞なので a は付かない', appliedMeaning: '文法的に成立せず、意味が確定しない' },
      { key: 'D', text: 'rices', correct: false, reasonCode: 'N_UNCOUNTABLE', note: 'rice は不可算なので複数形にできない', appliedMeaning: '「複数種類の米」という別の意味になる' },
    ],
  },
  {
    id: 3,
    tag: 'N-UNC',
    sceneTag: '家庭',
    functionTag: '申し出る',
    contextEn: 'You look tired after work.',
    ja: '熱いお茶を一杯入れましょうか。',
    template: 'I can make ___ for you.',
    headNoun: 'tea',
    headNounJa: 'お茶',
    countability: 'uncountable',
    gridVariant: 'unit-of',
    gridPatterns: ['{n}', 'a {n}', 'a cup of {n}', 'the {n}'],
    options: [
      { key: 'A', text: 'a cup of tea', correct: true, reasonCode: null, note: null, appliedMeaning: null },
      { key: 'B', text: 'tea', correct: false, reasonCode: 'N_UNIT_OF', note: '「一杯」なので単位表現が自然', appliedMeaning: 'お茶一般を入れる、という意味になり量がぼやける' },
      { key: 'C', text: 'a tea', correct: false, reasonCode: 'N_UNCOUNTABLE', note: 'tea は不可算なので a は付かない', appliedMeaning: '文法的に不自然で、意味が確定しない' },
      { key: 'D', text: 'the tea', correct: false, reasonCode: 'N_DEF_NEW', note: '初出で特定されていないので the は不適', appliedMeaning: '相手も知っている例のお茶を入れる、という意味になる' },
    ],
  },
  {
    id: 4,
    tag: 'V-MOD-DEO',
    sceneTag: '空港',
    functionTag: '理由・目的を問う',
    contextEn: 'She might miss her flight because of traffic.',
    ja: '彼女は今すぐ空港へ向かわなければならない。',
    template: 'She ___ go to the airport now.',
    poolUsed: ['have to', 'must', 'should', 'may'],
    options: [
      { key: 'A', text: 'has to', correct: true, reasonCode: null, note: null, appliedMeaning: null },
      { key: 'B', text: 'must', correct: false, reasonCode: 'V_MOD_SOURCE_MISMATCH', note: '外部事情ではなく話者の主観的な必要性に聞こえる', appliedMeaning: '話者が「絶対に必要だ」と個人的に強く思っている、という意味になる' },
      { key: 'C', text: 'should', correct: false, reasonCode: 'V_MOD_TOO_WEAK', note: '助言レベルで、緊急の必要性が伝わらない', appliedMeaning: '「そうした方がいいよ」という助言程度の弱さになる' },
      { key: 'D', text: 'may', correct: false, reasonCode: 'V_MOD_SENSE_MISMATCH', note: '許可・可能性の意味になり、必要性が伝わらない', appliedMeaning: '「行ってもよい（許可）」という意味に変わってしまう' },
    ],
  },
  {
    id: 6,
    tag: 'V-MOD-DYN',
    sceneTag: '教室',
    functionTag: '確認する',
    contextEn: 'The teacher asked about weekend plans.',
    ja: 'あなたは今週末に図書館で勉強するつもりですか。',
    template: '___ at the library this weekend?',
    baseVerb: 'study',
    poolUsed: ['(bare)', 'may', 'might', 'be going to'],
    options: [
      { key: 'A', text: 'Are you going to study', correct: true, reasonCode: null, note: null, appliedMeaning: null },
      { key: 'B', text: 'May you study', correct: false, reasonCode: 'V_MOD_TOO_WEAK', note: '許可・可能性のニュアンスになる', appliedMeaning: '勉強してもよいですか、という意味に変わってしまう' },
      { key: 'C', text: 'Might you study', correct: false, reasonCode: 'V_MOD_TOO_WEAK', note: 'さらに弱い可能性のニュアンスになる', appliedMeaning: '勉強するかもしれないか、という弱い推測になる' },
      { key: 'D', text: 'Do you study', correct: false, reasonCode: 'V_MOD_TENSE_MISMATCH', note: '習慣の現在になり、今週末の予定にならない', appliedMeaning: '普段図書館で勉強する習慣があるか、という意味になる' },
    ],
  },
  {
    id: 9,
    tag: 'V-MOD-DYN',
    sceneTag: '寮生活',
    functionTag: '情報を得る',
    contextEn: 'Every morning before school, she practices.',
    ja: '彼女は毎朝ピアノを弾く。',
    template: 'She ___ the piano every morning.',
    baseVerb: 'play',
    poolUsed: ['(bare)', 'can', 'would', 'may'],
    options: [
      { key: 'A', text: 'plays', correct: true, reasonCode: null, note: null, appliedMeaning: null },
      { key: 'B', text: 'can play', correct: false, reasonCode: 'V_MOD_SENSE_MISMATCH', note: '能力の意味になり、日常習慣の叙述と噛み合わない', appliedMeaning: '「弾ける（能力がある）」という意味になる' },
      { key: 'C', text: 'would play', correct: false, reasonCode: 'V_MOD_TENSE_MISMATCH', note: '過去や仮定の距離感が入る', appliedMeaning: '「（昔は／もし〜なら）弾いただろう」という距離のある意味になる' },
      { key: 'D', text: 'may play', correct: false, reasonCode: 'V_MOD_TOO_WEAK', note: '不確実な可能性の意味になる', appliedMeaning: '「弾くかもしれない」という不確かな意味になる' },
    ],
  },
  {
    id: 7,
    tag: 'V-TA',
    sceneTag: '職場',
    functionTag: '情報を得る',
    contextEn: 'The phone rang at 8pm.',
    ja: '電話が鳴ったとき、私は夕食を食べていた。',
    template: 'I ___ dinner when the phone rang.',
    options: [
      { key: 'A', text: 'was eating', correct: true, reasonCode: null, note: null, appliedMeaning: null },
      { key: 'B', text: 'ate', correct: false, reasonCode: 'V_ASPECT', note: '電話の瞬間に食事の途中である継続を表せない', appliedMeaning: '食べたという1回の完結した行為になり、電話との同時性が消える' },
      { key: 'C', text: 'have eaten', correct: false, reasonCode: 'V_TENSE', note: '現在完了と過去の1点は重ねられない', appliedMeaning: '「今までに食べたことがある」という現在時点の経験になる' },
      { key: 'D', text: 'had eaten', correct: false, reasonCode: 'V_ASPECT', note: '過去完了だと電話より前に食べ終わった順序になる', appliedMeaning: '電話が鳴る前に食事が完了していた、という順序の意味になる' },
    ],
  },
  {
    id: 8,
    tag: 'V-TA',
    sceneTag: '語学学校',
    functionTag: '理由・目的を問う',
    contextEn: 'She joined the English school six months ago.',
    ja: 'あなたはなぜ英語を勉強し始めたのですか。',
    template: 'Why ___ studying English?',
    options: [
      { key: 'A', text: 'did you start', correct: true, reasonCode: null, note: null, appliedMeaning: null },
      { key: 'B', text: 'have you started', correct: false, reasonCode: 'V_TENSE', note: '現在完了は現在時点までの経験を問い、開始時点を明示できない', appliedMeaning: '「今までに勉強し始めた経験があるか」という現在時点の話に変わる' },
      { key: 'C', text: 'were you starting', correct: false, reasonCode: 'V_ASPECT', note: '過去進行で「始める最中」は非常に狭い瞬間しか指せず不自然', appliedMeaning: '「始めようとしている最中だった」という不自然な進行の意味になる' },
      { key: 'D', text: 'had you started', correct: false, reasonCode: 'V_TENSE', note: '過去完了は別の過去時点を基準にする必要があり、基準が無い', appliedMeaning: '何か別の過去の出来事より前に始めていたか、という順序の意味になる' },
    ],
  },
];

export function formatFewShotBlock() {
  return FEW_SHOT_EXAMPLES.map((ex) => JSON.stringify(ex, null, 2)).join('\n\n');
}
